theme: minima
title: lhyqie's first github page
author: lhyqie
description: > # this means to ignore newlines until "baseurl:"
  Nothing is here. But less is more.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  lhyqie

show_excerpts: true # set to false to remove excerpts on the homepage
